call npx ts-node example-1.ts
call npx ts-node example-2.ts
call npx ts-node example-3.ts
call npx ts-node example-4.ts
call npx ts-node example-5.ts
call npx ts-node example-6.ts
call npx ts-node example-7.ts
call npx ts-node example-8.ts
call npx ts-node example-9.ts
call npx ts-node example-10.ts
call npx ts-node example-11.ts
call npx ts-node example-12.ts